spring:
  application:
    name: paypal-integration
paypal:
  client-id: YOUR_ID
  client-secret: YOUR_SECRET
  mode: YOUR_MODE  # we are using 'sandbox' mode for testing purposes and 'live' mode for production