spring:
  application:
    name: paypal-integration
paypal:
  client-id: ARtg1YnMAKYIpSVE_OePd-anVoOEiSBrhC5LX2O1Lp2x5SxlVbAvLGXihOYyZHY6Ao_B61-yaulNwlQX
  client-secret: EFMBFFUDiMCqVo0JOlBW9OncmShU6MTxYvuxVYlPTzeWargyWa9mGEmK80sa35lzABsjrL3Q25Yzdttg
  mode: sandbox  # we are using 'sandbox' mode for testing purposes and 'live' mode for production